//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EnumResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        internal static string CustomerCompanyStatus_Disable {
            get {
                return ResourceManager.GetString("CustomerCompanyStatus_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        internal static string CustomerCompanyStatus_Enable {
            get {
                return ResourceManager.GetString("CustomerCompanyStatus_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        internal static string CustomerStatus_Disable {
            get {
                return ResourceManager.GetString("CustomerStatus_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        internal static string CustomerStatus_Enable {
            get {
                return ResourceManager.GetString("CustomerStatus_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TheDayBeforeYesterday 的本地化字符串。
        /// </summary>
        internal static string DateFilterType_BeforeYesterday {
            get {
                return ResourceManager.GetString("DateFilterType_BeforeYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentMonth 的本地化字符串。
        /// </summary>
        internal static string DateFilterType_CurrentMonth {
            get {
                return ResourceManager.GetString("DateFilterType_CurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentWeek 的本地化字符串。
        /// </summary>
        internal static string DateFilterType_CurrentWeek {
            get {
                return ResourceManager.GetString("DateFilterType_CurrentWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentYear 的本地化字符串。
        /// </summary>
        internal static string DateFilterType_CurrentYear {
            get {
                return ResourceManager.GetString("DateFilterType_CurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LastMonth 的本地化字符串。
        /// </summary>
        internal static string DateFilterType_LastMonth {
            get {
                return ResourceManager.GetString("DateFilterType_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LastWeek 的本地化字符串。
        /// </summary>
        internal static string DateFilterType_LastWeek {
            get {
                return ResourceManager.GetString("DateFilterType_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MonthRang 的本地化字符串。
        /// </summary>
        internal static string DateFilterType_MonthRang {
            get {
                return ResourceManager.GetString("DateFilterType_MonthRang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NextWeek 的本地化字符串。
        /// </summary>
        internal static string DateFilterType_NextWeek {
            get {
                return ResourceManager.GetString("DateFilterType_NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TimePeriod 的本地化字符串。
        /// </summary>
        internal static string DateFilterType_TimePeriod {
            get {
                return ResourceManager.GetString("DateFilterType_TimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string DateFilterType_Today {
            get {
                return ResourceManager.GetString("DateFilterType_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tomorrow 的本地化字符串。
        /// </summary>
        internal static string DateFilterType_Tomorrow {
            get {
                return ResourceManager.GetString("DateFilterType_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yesterday 的本地化字符串。
        /// </summary>
        internal static string DateFilterType_Yesterday {
            get {
                return ResourceManager.GetString("DateFilterType_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Female 的本地化字符串。
        /// </summary>
        internal static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Male 的本地化字符串。
        /// </summary>
        internal static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        internal static string GroupStatus_Disable {
            get {
                return ResourceManager.GetString("GroupStatus_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        internal static string GroupStatus_Enable {
            get {
                return ResourceManager.GetString("GroupStatus_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string IssueDisposeType_UI {
            get {
                return ResourceManager.GetString("IssueDisposeType_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ManipulationSupport 的本地化字符串。
        /// </summary>
        internal static string IssueDisposeType_Use {
            get {
                return ResourceManager.GetString("IssueDisposeType_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Affirming 的本地化字符串。
        /// </summary>
        internal static string IssueProcessType_Affirming {
            get {
                return ResourceManager.GetString("IssueProcessType_Affirming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string IssueProcessType_Cancel {
            get {
                return ResourceManager.GetString("IssueProcessType_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish 的本地化字符串。
        /// </summary>
        internal static string IssueProcessType_Finish {
            get {
                return ResourceManager.GetString("IssueProcessType_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offering 的本地化字符串。
        /// </summary>
        internal static string IssueProcessType_Offering {
            get {
                return ResourceManager.GetString("IssueProcessType_Offering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RespondAscending 的本地化字符串。
        /// </summary>
        internal static string IssueSpendTimeSort_RespondAscending {
            get {
                return ResourceManager.GetString("IssueSpendTimeSort_RespondAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RespondDescending 的本地化字符串。
        /// </summary>
        internal static string IssueSpendTimeSort_RespondDescending {
            get {
                return ResourceManager.GetString("IssueSpendTimeSort_RespondDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SustainAscending 的本地化字符串。
        /// </summary>
        internal static string IssueSpendTimeSort_SustainAscending {
            get {
                return ResourceManager.GetString("IssueSpendTimeSort_SustainAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SustainDescending 的本地化字符串。
        /// </summary>
        internal static string IssueSpendTimeSort_SustainDescending {
            get {
                return ResourceManager.GetString("IssueSpendTimeSort_SustainDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string IssueStatus_Cancel {
            get {
                return ResourceManager.GetString("IssueStatus_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Closed 的本地化字符串。
        /// </summary>
        internal static string IssueStatus_Closed {
            get {
                return ResourceManager.GetString("IssueStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string IssueStatus_New {
            get {
                return ResourceManager.GetString("IssueStatus_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BeSolved 的本地化字符串。
        /// </summary>
        internal static string IssueStatus_Resolved {
            get {
                return ResourceManager.GetString("IssueStatus_Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unresolved 的本地化字符串。
        /// </summary>
        internal static string IssueStatus_Unresolved {
            get {
                return ResourceManager.GetString("IssueStatus_Unresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BugDisposition 的本地化字符串。
        /// </summary>
        internal static string IssueType_BUG {
            get {
                return ResourceManager.GetString("IssueType_BUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        internal static string IssueType_Other {
            get {
                return ResourceManager.GetString("IssueType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Q&amp;A 的本地化字符串。
        /// </summary>
        internal static string IssueType_QA {
            get {
                return ResourceManager.GetString("IssueType_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PeriodicalCheck 的本地化字符串。
        /// </summary>
        internal static string IssueType_RT {
            get {
                return ResourceManager.GetString("IssueType_RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MethodChange 的本地化字符串。
        /// </summary>
        internal static string IssueType_UI {
            get {
                return ResourceManager.GetString("IssueType_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free 的本地化字符串。
        /// </summary>
        internal static string IssueUIModifyType_Free {
            get {
                return ResourceManager.GetString("IssueUIModifyType_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotFree 的本地化字符串。
        /// </summary>
        internal static string IssueUIModifyType_Pay {
            get {
                return ResourceManager.GetString("IssueUIModifyType_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Append 的本地化字符串。
        /// </summary>
        internal static string IssueUIType_Append {
            get {
                return ResourceManager.GetString("IssueUIType_Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        internal static string IssueUIType_Modify {
            get {
                return ResourceManager.GetString("IssueUIType_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monthly 的本地化字符串。
        /// </summary>
        internal static string LocaleMaintenanceNumberType_Monthly {
            get {
                return ResourceManager.GetString("LocaleMaintenanceNumberType_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quarterly 的本地化字符串。
        /// </summary>
        internal static string LocaleMaintenanceNumberType_Quarterly {
            get {
                return ResourceManager.GetString("LocaleMaintenanceNumberType_Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yearly 的本地化字符串。
        /// </summary>
        internal static string LocaleMaintenanceNumberType_Yearly {
            get {
                return ResourceManager.GetString("LocaleMaintenanceNumberType_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fujitsu 的本地化字符串。
        /// </summary>
        internal static string OrganizationType_FCH {
            get {
                return ResourceManager.GetString("OrganizationType_FCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subcontractor 的本地化字符串。
        /// </summary>
        internal static string OrganizationType_Subcontractor {
            get {
                return ResourceManager.GetString("OrganizationType_Subcontractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        internal static string ProjectStatus_Expired {
            get {
                return ResourceManager.GetString("ProjectStatus_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        internal static string ProjectStatus_Repairing {
            get {
                return ResourceManager.GetString("ProjectStatus_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Daily 的本地化字符串。
        /// </summary>
        internal static string RemindDateType_Daily {
            get {
                return ResourceManager.GetString("RemindDateType_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monthly 的本地化字符串。
        /// </summary>
        internal static string RemindDateType_Monthly {
            get {
                return ResourceManager.GetString("RemindDateType_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Once 的本地化字符串。
        /// </summary>
        internal static string RemindDateType_OnlyOne {
            get {
                return ResourceManager.GetString("RemindDateType_OnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weekly 的本地化字符串。
        /// </summary>
        internal static string RemindDateType_Weekly {
            get {
                return ResourceManager.GetString("RemindDateType_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PlanReply 的本地化字符串。
        /// </summary>
        internal static string ReplyType_PlanReply {
            get {
                return ResourceManager.GetString("ReplyType_PlanReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RealityReply 的本地化字符串。
        /// </summary>
        internal static string ReplyType_RealityReply {
            get {
                return ResourceManager.GetString("ReplyType_RealityReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administrator 的本地化字符串。
        /// </summary>
        internal static string RoleType_Admin {
            get {
                return ResourceManager.GetString("RoleType_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assistant 的本地化字符串。
        /// </summary>
        internal static string RoleType_Assistant {
            get {
                return ResourceManager.GetString("RoleType_Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CustomerService 的本地化字符串。
        /// </summary>
        internal static string RoleType_CustomerService {
            get {
                return ResourceManager.GetString("RoleType_CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Managementer 的本地化字符串。
        /// </summary>
        internal static string RoleType_Managementer {
            get {
                return ResourceManager.GetString("RoleType_Managementer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subcontractor 的本地化字符串。
        /// </summary>
        internal static string RoleType_Subcontractor {
            get {
                return ResourceManager.GetString("RoleType_Subcontractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string Satisfaction_General {
            get {
                return ResourceManager.GetString("Satisfaction_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perfect 的本地化字符串。
        /// </summary>
        internal static string Satisfaction_Perfect {
            get {
                return ResourceManager.GetString("Satisfaction_Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Satisfactory 的本地化字符串。
        /// </summary>
        internal static string Satisfaction_Satisfactory {
            get {
                return ResourceManager.GetString("Satisfaction_Satisfactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish 的本地化字符串。
        /// </summary>
        internal static string ScheduleTaskRecordStatus_Done {
            get {
                return ResourceManager.GetString("ScheduleTaskRecordStatus_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unfinished 的本地化字符串。
        /// </summary>
        internal static string ScheduleTaskRecordStatus_Undone {
            get {
                return ResourceManager.GetString("ScheduleTaskRecordStatus_Undone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locale 的本地化字符串。
        /// </summary>
        internal static string ServiceLevel_Locale {
            get {
                return ResourceManager.GetString("ServiceLevel_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L&amp;R 的本地化字符串。
        /// </summary>
        internal static string ServiceLevel_LocaleAndRemote {
            get {
                return ResourceManager.GetString("ServiceLevel_LocaleAndRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote 的本地化字符串。
        /// </summary>
        internal static string ServiceLevel_Remote {
            get {
                return ResourceManager.GetString("ServiceLevel_Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware 的本地化字符串。
        /// </summary>
        internal static string ServiceRange_Hardware {
            get {
                return ResourceManager.GetString("ServiceRange_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software 的本地化字符串。
        /// </summary>
        internal static string ServiceRange_Software {
            get {
                return ResourceManager.GetString("ServiceRange_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5*8 的本地化字符串。
        /// </summary>
        internal static string ServiceRank_FiveMultiplyEight {
            get {
                return ResourceManager.GetString("ServiceRank_FiveMultiplyEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NBD 的本地化字符串。
        /// </summary>
        internal static string ServiceRank_NBD {
            get {
                return ResourceManager.GetString("ServiceRank_NBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        internal static string ServiceRank_Other {
            get {
                return ResourceManager.GetString("ServiceRank_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7*24 的本地化字符串。
        /// </summary>
        internal static string ServiceRank_SevenMultiplyTwentyfour {
            get {
                return ResourceManager.GetString("ServiceRank_SevenMultiplyTwentyfour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locale 的本地化字符串。
        /// </summary>
        internal static string ServiceType_Local {
            get {
                return ResourceManager.GetString("ServiceType_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote 的本地化字符串。
        /// </summary>
        internal static string ServiceType_Remote {
            get {
                return ResourceManager.GetString("ServiceType_Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        internal static string ToDoSchemeStatus_Disable {
            get {
                return ResourceManager.GetString("ToDoSchemeStatus_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        internal static string ToDoSchemeStatus_Enable {
            get {
                return ResourceManager.GetString("ToDoSchemeStatus_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string ToDoSchemeStatus_Stop {
            get {
                return ResourceManager.GetString("ToDoSchemeStatus_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locale 的本地化字符串。
        /// </summary>
        internal static string WorkPatterns_OnThepot {
            get {
                return ResourceManager.GetString("WorkPatterns_OnThepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote 的本地化字符串。
        /// </summary>
        internal static string WorkPatterns_Remote {
            get {
                return ResourceManager.GetString("WorkPatterns_Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HolidayMidnight 的本地化字符串。
        /// </summary>
        internal static string WorkShiftType_DayOffDeepIntoTheMight {
            get {
                return ResourceManager.GetString("WorkShiftType_DayOffDeepIntoTheMight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HolidayNon-S.Time 的本地化字符串。
        /// </summary>
        internal static string WorkShiftType_DayOffOutsideWorkingHours {
            get {
                return ResourceManager.GetString("WorkShiftType_DayOffOutsideWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HolidayS.Time 的本地化字符串。
        /// </summary>
        internal static string WorkShiftType_DayOffWorkingHours {
            get {
                return ResourceManager.GetString("WorkShiftType_DayOffWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeekdayMidnight 的本地化字符串。
        /// </summary>
        internal static string WorkShiftType_WorkdayDeepIntoTheMight {
            get {
                return ResourceManager.GetString("WorkShiftType_WorkdayDeepIntoTheMight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeekdayNon-S.Time 的本地化字符串。
        /// </summary>
        internal static string WorkShiftType_WorkdayOutsideWorkingHours {
            get {
                return ResourceManager.GetString("WorkShiftType_WorkdayOutsideWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeekdayS.Time 的本地化字符串。
        /// </summary>
        internal static string WorkShiftType_WorkdayWorkingHours {
            get {
                return ResourceManager.GetString("WorkShiftType_WorkdayWorkingHours", resourceCulture);
            }
        }
    }
}
