//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PropertyResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Asker 的本地化字符串。
        /// </summary>
        internal static string AskerId {
            get {
                return ResourceManager.GetString("AskerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Carbon Copy 的本地化字符串。
        /// </summary>
        internal static string CarbonCopyIds {
            get {
                return ResourceManager.GetString("CarbonCopyIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OtherE-mail 的本地化字符串。
        /// </summary>
        internal static string CarbonCopyOther {
            get {
                return ResourceManager.GetString("CarbonCopyOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CarbonCopy 的本地化字符串。
        /// </summary>
        internal static string CarbonCopyUsers {
            get {
                return ResourceManager.GetString("CarbonCopyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cause 的本地化字符串。
        /// </summary>
        internal static string Cause {
            get {
                return ResourceManager.GetString("Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContractAmount 的本地化字符串。
        /// </summary>
        internal static string ContractAmount {
            get {
                return ResourceManager.GetString("ContractAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cost 的本地化字符串。
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CostsRemark 的本地化字符串。
        /// </summary>
        internal static string CostsRemark {
            get {
                return ResourceManager.GetString("CostsRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreationDate 的本地化字符串。
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CustomerCompany 的本地化字符串。
        /// </summary>
        internal static string CustomerCompanyId {
            get {
                return ResourceManager.GetString("CustomerCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Superintendent 的本地化字符串。
        /// </summary>
        internal static string CustomerContactId {
            get {
                return ResourceManager.GetString("CustomerContactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer 的本地化字符串。
        /// </summary>
        internal static string CustomerId {
            get {
                return ResourceManager.GetString("CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HolidayMidnight 的本地化字符串。
        /// </summary>
        internal static string DayOffDeepIntoTheMightCoefficient {
            get {
                return ResourceManager.GetString("DayOffDeepIntoTheMightCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HolidayNon-S.Time 的本地化字符串。
        /// </summary>
        internal static string DayOffOutsideWorkingHoursCoefficient {
            get {
                return ResourceManager.GetString("DayOffOutsideWorkingHoursCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HolidayS.Time 的本地化字符串。
        /// </summary>
        internal static string DayOffWorkingHoursCoefficient {
            get {
                return ResourceManager.GetString("DayOffWorkingHoursCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department 的本地化字符串。
        /// </summary>
        internal static string DepartmentId {
            get {
                return ResourceManager.GetString("DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DisposeType 的本地化字符串。
        /// </summary>
        internal static string DisposeType {
            get {
                return ResourceManager.GetString("DisposeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duty 的本地化字符串。
        /// </summary>
        internal static string Duty {
            get {
                return ResourceManager.GetString("Duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndDate 的本地化字符串。
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnceExecuteDate 的本地化字符串。
        /// </summary>
        internal static string ExecuteDateByOnlyOn {
            get {
                return ResourceManager.GetString("ExecuteDateByOnlyOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FreeTime 的本地化字符串。
        /// </summary>
        internal static string ExecuteDateByOnlyOne {
            get {
                return ResourceManager.GetString("ExecuteDateByOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fax 的本地化字符串。
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FJSCContractAmount 的本地化字符串。
        /// </summary>
        internal static string FJSCContractAmount {
            get {
                return ResourceManager.GetString("FJSCContractAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FreeTime 的本地化字符串。
        /// </summary>
        internal static string FreeWorkTime {
            get {
                return ResourceManager.GetString("FreeWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FullName 的本地化字符串。
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sex 的本地化字符串。
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProjectGroup 的本地化字符串。
        /// </summary>
        internal static string GroupId {
            get {
                return ResourceManager.GetString("GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InstallDate 的本地化字符串。
        /// </summary>
        internal static string InstallDate {
            get {
                return ResourceManager.GetString("InstallDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installer 的本地化字符串。
        /// </summary>
        internal static string Installer {
            get {
                return ResourceManager.GetString("Installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssueTag 的本地化字符串。
        /// </summary>
        internal static string IssueTag {
            get {
                return ResourceManager.GetString("IssueTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KeyWord 的本地化字符串。
        /// </summary>
        internal static string KeyWord {
            get {
                return ResourceManager.GetString("KeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LastModifyUser 的本地化字符串。
        /// </summary>
        internal static string LastModifyUser {
            get {
                return ResourceManager.GetString("LastModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Licence 的本地化字符串。
        /// </summary>
        internal static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LiveDate 的本地化字符串。
        /// </summary>
        internal static string LiveDate {
            get {
                return ResourceManager.GetString("LiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocalWorking 的本地化字符串。
        /// </summary>
        internal static string LocaleMaintenanceNumber {
            get {
                return ResourceManager.GetString("LocaleMaintenanceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MobileNo 的本地化字符串。
        /// </summary>
        internal static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewPassword 的本地化字符串。
        /// </summary>
        internal static string NewPwd {
            get {
                return ResourceManager.GetString("NewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrganizationId 的本地化字符串。
        /// </summary>
        internal static string OrganizationId {
            get {
                return ResourceManager.GetString("OrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrganizationType 的本地化字符串。
        /// </summary>
        internal static string OrganizationType {
            get {
                return ResourceManager.GetString("OrganizationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OActualAcceptance 的本地化字符串。
        /// </summary>
        internal static string OutsourcingActualAcceptanceDate {
            get {
                return ResourceManager.GetString("OutsourcingActualAcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OActualDistribution 的本地化字符串。
        /// </summary>
        internal static string OutsourcingActualDistributionDate {
            get {
                return ResourceManager.GetString("OutsourcingActualDistributionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OutsourcingAmount 的本地化字符串。
        /// </summary>
        internal static string OutsourcingAmount {
            get {
                return ResourceManager.GetString("OutsourcingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OExpectAcceptance 的本地化字符串。
        /// </summary>
        internal static string OutsourcingExpectAcceptanceDate {
            get {
                return ResourceManager.GetString("OutsourcingExpectAcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OExpectDistribution 的本地化字符串。
        /// </summary>
        internal static string OutsourcingExpectDistributionDate {
            get {
                return ResourceManager.GetString("OutsourcingExpectDistributionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone 的本地化字符串。
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PhoneNo. 的本地化字符串。
        /// </summary>
        internal static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PlanDate 的本地化字符串。
        /// </summary>
        internal static string PlanDate {
            get {
                return ResourceManager.GetString("PlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PlanServiceTime 的本地化字符串。
        /// </summary>
        internal static string PlanServiceTime {
            get {
                return ResourceManager.GetString("PlanServiceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PlanServiceType 的本地化字符串。
        /// </summary>
        internal static string PlanServiceType {
            get {
                return ResourceManager.GetString("PlanServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PlanServiceStaff 的本地化字符串。
        /// </summary>
        internal static string PlanServiceUserNo {
            get {
                return ResourceManager.GetString("PlanServiceUserNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FCH Superintendent 的本地化字符串。
        /// </summary>
        internal static string PMId {
            get {
                return ResourceManager.GetString("PMId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project 的本地化字符串。
        /// </summary>
        internal static string ProjectId {
            get {
                return ResourceManager.GetString("ProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project 的本地化字符串。
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProjectView 的本地化字符串。
        /// </summary>
        internal static string ProjectView {
            get {
                return ResourceManager.GetString("ProjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PublishDate 的本地化字符串。
        /// </summary>
        internal static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publisher 的本地化字符串。
        /// </summary>
        internal static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ 的本地化字符串。
        /// </summary>
        internal static string QQ {
            get {
                return ResourceManager.GetString("QQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DisposeDate 的本地化字符串。
        /// </summary>
        internal static string RealityDate {
            get {
                return ResourceManager.GetString("RealityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ServiceStartTime 的本地化字符串。
        /// </summary>
        internal static string RealityServiceBeginTime {
            get {
                return ResourceManager.GetString("RealityServiceBeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ServiceEndTime 的本地化字符串。
        /// </summary>
        internal static string RealityServiceEndTime {
            get {
                return ResourceManager.GetString("RealityServiceEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ServiceType 的本地化字符串。
        /// </summary>
        internal static string RealityServiceType {
            get {
                return ResourceManager.GetString("RealityServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ServiceStaff 的本地化字符串。
        /// </summary>
        internal static string RealityServiceUserNo {
            get {
                return ResourceManager.GetString("RealityServiceUserNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ServiceStaffList 的本地化字符串。
        /// </summary>
        internal static string RealityServiceUsers {
            get {
                return ResourceManager.GetString("RealityServiceUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RemindDateType 的本地化字符串。
        /// </summary>
        internal static string RemindDateType {
            get {
                return ResourceManager.GetString("RemindDateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RepeatPwd 的本地化字符串。
        /// </summary>
        internal static string RepeatPwd {
            get {
                return ResourceManager.GetString("RepeatPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReplyDate 的本地化字符串。
        /// </summary>
        internal static string ReplyDate {
            get {
                return ResourceManager.GetString("ReplyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReplyType 的本地化字符串。
        /// </summary>
        internal static string ReplyType {
            get {
                return ResourceManager.GetString("ReplyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Roles 的本地化字符串。
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seller 的本地化字符串。
        /// </summary>
        internal static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShortName 的本地化字符串。
        /// </summary>
        internal static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SoftwereVersion 的本地化字符串。
        /// </summary>
        internal static string SoftwereVersion {
            get {
                return ResourceManager.GetString("SoftwereVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartDate 的本地化字符串。
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TagName 的本地化字符串。
        /// </summary>
        internal static string TagName {
            get {
                return ResourceManager.GetString("TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TestingDate 的本地化字符串。
        /// </summary>
        internal static string TestingDate {
            get {
                return ResourceManager.GetString("TestingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TravelCosts 的本地化字符串。
        /// </summary>
        internal static string TravelCosts {
            get {
                return ResourceManager.GetString("TravelCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModifyType 的本地化字符串。
        /// </summary>
        internal static string UIModifyType {
            get {
                return ResourceManager.GetString("UIModifyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string UIType {
            get {
                return ResourceManager.GetString("UIType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WBS No 的本地化字符串。
        /// </summary>
        internal static string WBS {
            get {
                return ResourceManager.GetString("WBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WBSActualAcceptance 的本地化字符串。
        /// </summary>
        internal static string WBSActualAcceptanceDate {
            get {
                return ResourceManager.GetString("WBSActualAcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WBSExpectAcceptance 的本地化字符串。
        /// </summary>
        internal static string WBSExpectAcceptanceDate {
            get {
                return ResourceManager.GetString("WBSExpectAcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window 的本地化字符串。
        /// </summary>
        internal static string WindowId {
            get {
                return ResourceManager.GetString("WindowId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeekdayMidnight 的本地化字符串。
        /// </summary>
        internal static string WorkdayDeepIntoTheMightCoefficient {
            get {
                return ResourceManager.GetString("WorkdayDeepIntoTheMightCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeekdayNon-S.Time 的本地化字符串。
        /// </summary>
        internal static string WorkdayOutsideWorkingHoursCoefficient {
            get {
                return ResourceManager.GetString("WorkdayOutsideWorkingHoursCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeekdayS.Time 的本地化字符串。
        /// </summary>
        internal static string WorkdayWorkingHoursCoefficient {
            get {
                return ResourceManager.GetString("WorkdayWorkingHoursCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StaffNumber 的本地化字符串。
        /// </summary>
        internal static string WorkerNumber {
            get {
                return ResourceManager.GetString("WorkerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Staffs 的本地化字符串。
        /// </summary>
        internal static string Workers {
            get {
                return ResourceManager.GetString("Workers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkingHour 的本地化字符串。
        /// </summary>
        internal static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkPattern 的本地化字符串。
        /// </summary>
        internal static string WorkPatterns {
            get {
                return ResourceManager.GetString("WorkPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OccasionType 的本地化字符串。
        /// </summary>
        internal static string WorkShiftType {
            get {
                return ResourceManager.GetString("WorkShiftType", resourceCulture);
            }
        }
    }
}
