//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportForms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportForms() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ReportForms", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AllIssue 的本地化字符串。
        /// </summary>
        internal static string AllIssue {
            get {
                return ResourceManager.GetString("AllIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClosedIssue 的本地化字符串。
        /// </summary>
        internal static string ClosedIssue {
            get {
                return ResourceManager.GetString("ClosedIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creater 的本地化字符串。
        /// </summary>
        internal static string Creater {
            get {
                return ResourceManager.GetString("Creater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer 的本地化字符串。
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follower 的本地化字符串。
        /// </summary>
        internal static string Follower {
            get {
                return ResourceManager.GetString("Follower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssueCountTotalList 的本地化字符串。
        /// </summary>
        internal static string IssueCountTotalList {
            get {
                return ResourceManager.GetString("IssueCountTotalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssueType 的本地化字符串。
        /// </summary>
        internal static string IssueType {
            get {
                return ResourceManager.GetString("IssueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *System will show the list by checkbox that you checked. 的本地化字符串。
        /// </summary>
        internal static string MadeTheListByCheckedBox {
            get {
                return ResourceManager.GetString("MadeTheListByCheckedBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewIssue 的本地化字符串。
        /// </summary>
        internal static string NewIssue {
            get {
                return ResourceManager.GetString("NewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PatchCountTotalList 的本地化字符串。
        /// </summary>
        internal static string PatchCountTotalList {
            get {
                return ResourceManager.GetString("PatchCountTotalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PathCount 的本地化字符串。
        /// </summary>
        internal static string PathCount {
            get {
                return ResourceManager.GetString("PathCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project 的本地化字符串。
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProjectTags 的本地化字符串。
        /// </summary>
        internal static string ProjectTags {
            get {
                return ResourceManager.GetString("ProjectTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReportGroup 的本地化字符串。
        /// </summary>
        internal static string ReportGroup {
            get {
                return ResourceManager.GetString("ReportGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResolvedIssue 的本地化字符串。
        /// </summary>
        internal static string ResolvedIssue {
            get {
                return ResourceManager.GetString("ResolvedIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 time 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnresolvedIssue 的本地化字符串。
        /// </summary>
        internal static string UnresolvedIssue {
            get {
                return ResourceManager.GetString("UnresolvedIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UseredTime 的本地化字符串。
        /// </summary>
        internal static string UseredTime {
            get {
                return ResourceManager.GetString("UseredTime", resourceCulture);
            }
        }
    }
}
